default_language: "id"

web-host: 0.0.0.0
web-port: 8080

discord-webhook: "https://discord.com/api/webhooks/xxxxx"
ranks:
  ELITE:
    price: 15.000
    image: "textures/ui/promo_bee"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"
  VIP:
    price: 20.000
    image: "textures/ui/promo_spider"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"
  MVP:
    price: 30.000
    description: "Rank premium dengan fitur khusus."
    image: "textures/ui/promo_chicken"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"
  Legends:
    price: 40.000
    image: "textures/ui/promo_wolf"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"
  Angel:
    price: 60.000
    image: "textures/ui/promo_creeper"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"
  ExCluSive:
    price: 80.000
    image: "textures/ui/realms_key_art"
    title: "§l§aVIP Rank"
    content: "§fBenefit VIP:\n§7- Fly\n§7- Kit VIP\n§7- Prefix VIP"

payment_methods:
  - GoPay
  - DANA
  - OVO
  - Paypal

messages:
  rank_purchased: "Terima kasih! Permintaan top-up Anda sedang diproses oleh admin."
  notify_admin: "Pemain %player% telah meminta top-up rank %rank% menggunakan metode %method%."
  invalid_phone: "Nomor telepon tidak valid. Masukkan nomor telepon yang benar."
  invalid_gamertag: "Nama gamertag tidak valid. Masukkan nama yang benar."
  payment_success: "Pembayaran berhasil diproses. Rank %rank% telah diberikan kepada pemain."
  payment_rejected: "Pembayaran ditolak oleh admin."
